<a href="https://colab.research.google.com/github/bhardwajsudhanshu/Play_with_Pytorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not avaialable. using cpu")

GPU is available
using GPU: Tesla T4


**Creating** **Tensor**

In [ ]:
#Using Empty
# this empty function create a space so that later we can assign the values
a = torch.empty(2,3)

In [ ]:
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
#using zeroes
# we can use this zero tensor to create a neural network let suppoise initially we want to assign zero value to biases we can use this
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.6929, 0.7754, 0.4452],
        [0.7709, 0.7395, 0.3308]])

In [ ]:
#use of seed
torch.rand(2,3)

tensor([[0.3808, 0.9080, 0.4027],
        [0.1358, 0.8977, 0.0877]])

In [ ]:
#use of manual seed
# we are using seed because random will always generate diff values for every rand run what if my colleague uses the same code and he need the same ouput for rand also for tHAT we will use maual seed or seed it is basically reproducability.
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[2,3,4],[4,5,6]])

tensor([[2, 3, 4],
        [4, 5, 6]])

In [ ]:
#arange
print("using arange: ", torch.arange(0,10,2))

#linspace
print("using linspace: ", torch.linspace(0,10,10))

#using eye
print("using eye for identity matrix: ", torch.eye(5))
# using full
print("using full: ", torch.full((3,3),5))

using arange:  tensor([0, 2, 4, 6, 8])
using linspace:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye for identity matrix:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full:  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensor** **Shapes**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[         0, 1055162816,          0],
        [         0,          1,          6]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

**Tensor Data Types**

In [ ]:
#find data type
x.dtype

torch.int64

In [ ]:
#asssign data type
torch.tensor([1.0,2.3,4.0],dtype = torch.int32)

tensor([1, 2, 4], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,4],dtype = torch.float32)

tensor([1., 2., 4.])

In [ ]:
#using to we can convert data type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Scaler Operation**

In [ ]:
#addition
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [ ]:
x//2

tensor([[0, 1, 1],
        [2, 2, 3]])

In [ ]:
#addition
x+2
#sub
x-2
#mul
x*2
#div
x/2
#int div
x//2
#pow
x**2
#mod
x%2

tensor([[1, 0, 1],
        [0, 1, 0]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [ ]:
#addition
a+b
#sub
a-b
#mul
a*b
#div
a/b
#int div
a//b
#pow
a**b
#mod
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [ ]:
c = torch.tensor([-1.0,2.0,-3.0])

In [ ]:
#abs
abs(c)

tensor([1., 2., 3.])

In [ ]:
torch.abs(c)

tensor([1., 2., 3.])

In [ ]:
d = torch.tensor([-1,2,-3])

In [ ]:
abs(d)

tensor([1, 2, 3])

In [ ]:
torch.abs(d)

tensor([1, 2, 3])

In [ ]:
e = torch.tensor([1.9,2.2,5.3,6.3])

In [ ]:
#round
torch.round(e)

tensor([2., 2., 5., 6.])

In [ ]:
#ceil
torch.ceil(e)

tensor([2., 3., 6., 7.])

In [ ]:
#floor
torch.floor(e)

tensor([1., 2., 5., 6.])

In [ ]:
#clamp
#ceil
torch.clamp(e, min=2,max=3)

tensor([2.0000, 2.2000, 3.0000, 3.0000])

**Reduction Operation**

In [ ]:
f = torch.randint(size=(2,3),low=0,high=10)
f

tensor([[0, 1, 9],
        [9, 8, 0]])

In [ ]:
#addition
torch.sum(f)
#sum along columns
torch.sum(f, dim=0)
#sem along rows
torch.sum(f, dim=1)


tensor([10, 17])

In [ ]:
#sum along columns
torch.sum(f, dim=0)


tensor([9, 9, 9])

In [ ]:
#sem along rows
torch.sum(f, dim=1)

tensor([10, 17])

In [ ]:
g = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
g

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [ ]:
#mean
#remember mean always works with the float data type
torch.mean(g)

tensor(4.6667)

In [ ]:
#col wise mean
torch.mean(g,dim=0)

tensor([8.0000, 2.5000, 3.5000])

In [ ]:
#row wise mean
torch.mean(g,dim=1)

tensor([2.3333, 7.0000])

In [ ]:
#mean
torch.median(g)

tensor(5.)

In [ ]:
#col wise median
torch.median(g,dim=0)

torch.return_types.median(
values=tensor([7., 0., 0.]),
indices=tensor([0, 0, 0]))

In [ ]:
#row wise median
torch.median(g,dim=1)

torch.return_types.median(
values=tensor([0., 7.]),
indices=tensor([2, 2]))

In [ ]:
#max and min
torch.max(g)
torch.min(g)

tensor(0.)

In [ ]:
#product
torch.prod(g)

tensor(0.)

In [ ]:
#standard deviation
torch.std(g)

tensor(3.8297)

In [ ]:
#variance
torch.var(g)

tensor(14.6667)

In [ ]:
#argmax
#it tells us ther position of biggest item in tensors
torch.argmax(g)

tensor(3)

In [ ]:
#argmin
#it tells us ther position of smallest item in tensors
torch.argmin(g)

tensor(1)

**Matrix Operation**

In [ ]:
h = torch.randint(size=(2,3), low=0, high=10)
i = torch.randint(size=(3,2), low=0, high=10)
print(h)
print(i)

tensor([[3, 9, 4],
        [0, 5, 7]])
tensor([[5, 9],
        [9, 7],
        [5, 9]])


In [ ]:
#matrix multiplication
torch.matmul(h,i)

tensor([[116, 126],
        [ 80,  98]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(g,0,1)

tensor([[7., 9.],
        [0., 5.],
        [0., 7.]])

In [ ]:
j = torch.randint(size=(3,3),low=0, high=10, dtype=torch.float32)
j

tensor([[8., 9., 7.],
        [9., 2., 6.],
        [7., 7., 8.]])

In [ ]:
#determinant
torch.det(j)

tensor(-135.0000)

In [ ]:
#inverse
torch.inverse(j)

tensor([[ 0.1926,  0.1704, -0.2963],
        [ 0.2222, -0.1111, -0.1111],
        [-0.3630, -0.0519,  0.4815]])

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10)
l = torch.randint(size=(2,3), low=0, high=10)
print(k)
print(l)

tensor([[3, 6, 1],
        [5, 5, 0]])
tensor([[4, 3, 8],
        [8, 3, 3]])


In [ ]:
#greater than
k>l
#less than
k<l
#equal to
k == l
#not equal to
k != l
#greater than equal to
k>=l
#smaller than equal to
k<=l

tensor([[ True, False,  True],
        [ True, False,  True]])

**special Function**

In [ ]:
m = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
m

tensor([[5., 0., 6.],
        [4., 0., 8.]])

In [ ]:
#log
torch.log(m)

tensor([[1.6094,   -inf, 1.7918],
        [1.3863,   -inf, 2.0794]])

In [ ]:
#sqrt
torch.sqrt(m)

tensor([[2.2361, 0.0000, 2.4495],
        [2.0000, 0.0000, 2.8284]])

In [ ]:
#exp
torch.exp(m)

tensor([[1.4841e+02, 1.0000e+00, 4.0343e+02],
        [5.4598e+01, 1.0000e+00, 2.9810e+03]])

In [ ]:
#sigmoid
torch.sigmoid(m)

tensor([[0.9933, 0.5000, 0.9975],
        [0.9820, 0.5000, 0.9997]])

In [ ]:
#sqrt
torch.softmax(m, dim=0)

tensor([[0.7311, 0.5000, 0.1192],
        [0.2689, 0.5000, 0.8808]])

In [ ]:
#relu
torch.relu(m)

tensor([[5., 0., 6.],
        [4., 0., 8.]])

**Inplace operation**

In [ ]:
n = torch.rand(2,3)
o = torch.rand(2,3)
print(n)
print(o)

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])
tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])


In [ ]:
n+o
#here this creates a new tensor and occupies more space
# so we need another approach to add the tensor and does not use extra space

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
#good pproach
n.add_(o)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
n

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
o

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
torch.relu(m)
#this is completely new tensor and uses extra space

tensor([[5., 0., 6.],
        [4., 0., 8.]])

In [ ]:
m.relu_()
#this does not uses extra space

tensor([[5., 0., 6.],
        [4., 0., 8.]])

In [ ]:
m

tensor([[5., 0., 6.],
        [4., 0., 8.]])

**Copying a Tensor**

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
b
#the changes reflects in both a and b

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
id(a)

133234274314240

In [ ]:
id(b)
#pointing to same both a and b

133234274314240

In [ ]:
# to overcome above problem
#we can use this
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
b

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.7668,  0.1659],
        [ 0.4393,  0.2243,  0.8935]])

In [ ]:
b

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

**Tensor Operations on GPU**

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
#creating a new tensor on gpu
#now this tensor is designed using gpu
torch.rand((2,3), device=device)

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938]], device='cuda:0')

In [ ]:
#moving an existing tensor which is on cpu to gpu
a = torch.rand(2,3)
a

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [ ]:
b = a.to(device)
#now this is move to gpu

In [ ]:
b+5

tensor([[5.3957, 5.6017, 5.4234],
        [5.5224, 5.4175, 5.0340]], device='cuda:0')

In [ ]:
#reshape
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Numpy and Pytorch**

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])

In [ ]:
type(c)

numpy.ndarray